version: "3.9"
services:
  medis:
   container_name: medis-docker
   build:
     context: .
   entrypoint: python -u app/main.py 0.0.0.0 6689
   ports:
     - 6689:6689
   volumes:
     - ./persistors_data:/app/persistors
